<?php

/**
 * @file
 * Functions to support theming in the Test task theme theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function test_task_theme_preprocess_html(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function test_task_theme_preprocess_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function test_task_theme_preprocess_node(&$variables) {

  $termStorage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
  $ids = $termStorage->getQuery()
    ->condition('vid', 'vocabulary')
    ->execute();

  $vocabulary = [];
  foreach ($termStorage->loadMultiple($ids) as $item) {
    $vocabulary[$item->id()] = $item->label();
  }

  $description = $variables['content']['field_news_description'][0]['#text'];
  foreach ($vocabulary as $taxonomy) {
    $description = str_replace($taxonomy, "<a title='Descpiption' href=''>$taxonomy</a>", $description);
  }
  $variables['content']['field_news_description'][0]['#text'] = $description;
  $variables['content']['field_news_description'][0]['#format'] = 'full_html';
}
