# Schema for the configuration files of the Test task module.
test_task.settings:
  type: config_object
  label: 'Test task settings'
  mapping:
    example:
      type: string
      label: 'Example'
